apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveltrack
  namespace: traveltrack
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traveltrack
  template:
    metadata:
      labels:
        app: traveltrack
    spec:
      containers:
        - name: traveltrack
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: traveltrack-config
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false


#semgrep --config=p/owasp-top-ten --json: 
#Se corrigió la alerta detectada por Semgrep relacionada con la posible escalación de privilegios.
#Se añadió la directiva allowPrivilegeEscalation: false al bloque securityContext del contenedor principal.
#Esto garantiza que ningún proceso dentro del contenedor pueda elevar privilegios, 
#alineándose con las prácticas recomendadas de seguridad de Kubernetes y OWASP.
