apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveltrack
  namespace: traveltrack
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traveltrack
  template:
    metadata:
      labels:
        app: traveltrack
    spec:
      containers:
        - name: traveltrack
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: traveltrack-config
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
